### ISSUE TITLE
Feature Request: Layout Simplification 

### ISSUE THREAD

**Issue by yschimke** [Splitties/WffDsl#16]
When converting from WatchFaceStudio generated XML, ways to simplify.

At it's simplest, warn on redundant default values, such as Height/Width matching parent, or default alpha.

But potentially also simpler layout APIs than width/height/x/y. Not sure what this is.

**Comment by LouisCAD** [comment]
Something like `Offset` from Compose UI Graphics?

**Comment by yschimke** [comment]
Yeah, I'm not sure.

In compose terms, a child often knows it size, and a parent knows the placement.

Or maybe it's a simple Rect, with defaults of match parent?

**Comment by LouisCAD** [comment]
Things already default to match-parent in WffDsl, if you omit the width and height arguments, keeping the default value.

**Comment by yschimke** [comment]
Fair enough.
